name: FakePlayersOnline
main: me.fromgate.fakeplayersonline.FakePlayersOnline
version: 0.1.7
author: fromgate
softdepend: [Citizens,ProtocolLib]
commands:
   fpo:
      description: FakePlayersOnline commands
      usage: |
           /fpo help